language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install: "bundle install --jobs 8"
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - 3.0.2
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails60.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails42.gemfile
  fast_finish: true
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
